spring:
  application:
    name: charitytrades

  datasource:
    url: jdbc:postgresql://localhost:5432/charitytrades
    username: hadikhamsi
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

globalgiving:
  api:
    key: f94e500d-d161-4c9b-927e-62df28d0af72
    base-url: https://api.globalgiving.org
  rate-limit:
    requests-per-second: 2
